<?php

use Illuminate\Database\Seeder;
use App\Role;
use App\User;


class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*$role_user = Role::where('name','Usuario')->first();
        $role_admin = Role::where('name','admin')->first();
        $role_jlogistica = Role::where('name','JefeLogistica')->first();
        $role_joperacion = Role::where('name','JefeOperacion')->first();
        $role_suser = Role::where('name','Programador')->first();
        $role_client = Role::where('name','Cliente')->first();
        $role_gener = Role::where('name','Generador')->first();
        $role_auxlogistica = Role::where('name','AuxiliarLogistica')->first();
        $role_asistlogistica = Role::where('name','AsistenteLogistica')->first();
        $role_sturno = Role::where('name','SupervisorTurno')->first();
        $role_ealmacen = Role::where('name','EncargadoAlmacen')->first();
        $role_ehorno = Role::where('name','EncargadoHorno')->first();*/

        $user = new User();
        $user->name = 'Luis';
        $user->email = 'Sistemas@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Programador';
        $user->UsRolDesc = 'Programador de Software';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 1;
        $user->UsRol2 = 'Hseq';
        $user->UsRolDesc2 = 'Ingeniero de seguridad y salud Ocupacional';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Andres';
        $user->email = 'Sistemas3@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Programador';
        $user->UsRolDesc = 'Programador de Software';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 2;
        $user->UsRol2 = 'Hseq';
        $user->UsRolDesc2 = 'Ingeniero de seguridad y salud Ocupacional';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Heidy';
        $user->email = 'Sistemas2@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Programador';
        $user->UsRolDesc = 'Programador de Software';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 3;
        $user->UsRol2 = 'Hseq';
        $user->UsRolDesc2 = 'Ingeniero de seguridad y salud Ocupacional';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Victor';
        $user->email = 'dirtecnica@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'JefeOperaciones';
        $user->UsRolDesc = 'Jefe de area Operaciones';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 4;
        $user->UsRol2 = 'Supervisor';
        $user->UsRolDesc2 = '';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Jhon';
        $user->email = 'logistica@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'JefeLogistica';
        $user->UsRolDesc = 'Jefe de area Logistica';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 5;
        $user->UsRol2 = 'AsistenteLogistica';
        $user->UsRolDesc2 = 'Asistente de area Logistica';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Duvan';
        $user->email = 'asistentelogistica@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'AsistenteLogistica';
        $user->UsRolDesc = 'Asistente de area Logistica';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 6;
        $user->UsRol2 = 'AsistenteLogistica';
        $user->UsRolDesc2 = 'Asistente de area Logistica';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Jhonatan';
        $user->email = 'auxiliarlogistico@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'AsistenteLogistica';
        $user->UsRolDesc = 'Asistente';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 7;
        $user->UsRol2 = 'AsistenteLogistica';
        $user->UsRolDesc2 = 'Asistente de area Logistica';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Andres';
        $user->email = 'ingenierohseq@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Hseq';
        $user->UsRolDesc = 'Ingeniero de seguridad y salud Ocupacional';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 8;
        $user->UsRol2 = 'JefeLogistica';
        $user->UsRolDesc2 = 'Jefe de area Logistica';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'David';
        $user->email = 'gerenteplanta@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'AdministradorPlanta';
        $user->UsRolDesc = 'Jefe de Planta';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 27;
        $user->UsRol2 = 'JefeOperaciones';
        $user->UsRolDesc2 = 'Jefe de area Operaciones';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Camilo';
        $user->email = 'ingtratamiento1@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Supervisor';
        $user->UsRolDesc = 'Supervisor de Turno';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 10;
        $user->UsRol2 = 'Supervisor';
        $user->UsRolDesc2 = 'Supervisor de Turno';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Oscar';
        $user->email = 'ingtratamiento3@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Supervisor';
        $user->UsRolDesc = 'Supervisor de Turno';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 11;
        $user->UsRol2 = 'Supervisor';
        $user->UsRolDesc2 = 'Supervisor de Turno';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'William';
        $user->email = 'ingtratamiento2@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Supervisor';
        $user->UsRolDesc = 'Supervisor de Turno';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 12;
        $user->UsRol2 = 'Supervisor';
        $user->UsRolDesc2 = 'Supervisor de Turno';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Alfonso';
        $user->email = 'Conductor1@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Conductor';
        $user->UsRolDesc = 'Conductor';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 13;
        $user->UsRol2 = 'Conductor';
        $user->UsRolDesc2 = 'Conductor';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Victor';
        $user->email = 'Conductor2@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Conductor';
        $user->UsRolDesc = 'Conductor';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 14;
        $user->UsRol2 = 'Conductor';
        $user->UsRolDesc2 = 'Conductor';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Jose';
        $user->email = 'Conductor3@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Conductor';
        $user->UsRolDesc = 'Conductor';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 15;
        $user->UsRol2 = 'Conductor';
        $user->UsRolDesc2 = 'Conductor';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Hilber';
        $user->email = 'Conductor4@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Conductor';
        $user->UsRolDesc = 'Conductor';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 16;
        $user->UsRol2 = 'Conductor';
        $user->UsRolDesc2 = 'Conductor';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Juan';
        $user->email = 'Conductor5@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Conductor';
        $user->UsRolDesc = 'Conductor';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 17;
        $user->UsRol2 = 'Conductor';
        $user->UsRolDesc2 = 'Conductor';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Orlando';
        $user->email = 'subgerencia@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'AdministradorBogota';
        $user->UsRolDesc = 'Administrador de la sede Bogotá';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 18;
        $user->UsRol2 = 'JefeComercial';
        $user->UsRolDesc2 = 'Director Comercial';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Maria';
        $user->email = 'CuentasCorporativas@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Comercial';
        $user->UsRolDesc = 'Ejecutivo Comercial';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 19;
        $user->UsRol2 = 'Comercial';
        $user->UsRolDesc2 = 'Ejecutivo Comercial';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Lorena';
        $user->email = 'Comercial2@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Comercial';
        $user->UsRolDesc = 'Ejecutivo Comercial';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 20;
        $user->UsRol2 = 'Comercial';
        $user->UsRolDesc2 = 'Ejecutivo Comercial';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Briyith';
        $user->email = 'Comercial1@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Comercial';
        $user->UsRolDesc = 'Ejecutivo Comercial';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 21;
        $user->UsRol2 = 'Comercial';
        $user->UsRolDesc2 = 'Ejecutivo Comercial';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Miguel';
        $user->email = 'Comercial3@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Comercial';
        $user->UsRolDesc = 'Ejecutivo Comercial';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 22;
        $user->UsRol2 = 'Comercial';
        $user->UsRolDesc2 = 'Ejecutivo Comercial';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Lady';
        $user->email = 'servicomercial@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'AsistenteComercial';
        $user->UsRolDesc = 'Asistente Comercial';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 24;
        $user->UsRol2 = 'AsistenteComercial';
        $user->UsRolDesc2 = 'Asistente Comercial';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Nidia';
        $user->email = 'Gestion@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'Tesorera';
        $user->UsRolDesc = 'Tesoreria y facturacion';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 25;
        $user->UsRol2 = 'Tesorera';
        $user->UsRolDesc2 = 'Tesoreria y facturacion';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Andres';
        $user->email = 'gerencia@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'AdministradorBogota';
        $user->UsRolDesc = 'Gerente General PROSARC S.A. ESP.';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 26;
        $user->UsRol2 = 'AdministradorPlanta';
        $user->UsRolDesc2 = 'Jefe de Planta';
        $user->DeleteUser = 0;
        $user->save();

        $user = new User();
        $user->name = 'Leider';
        $user->email = 'jefehseq@prosarc.com.co';
        $user->email_verified_at = now();
        $user->password = bcrypt('secret');
        $user->UsAvatar = 'robot400x400.gif';
        $user->UsStatus = 'Activo';
        $user->UsSlug = hash('sha256', rand().time().$user->email);
        $user->UsRol = 'jefehseq';
        $user->UsRolDesc = 'Jefe de HSEQ';
        $user->updated_by = 'Sistemas@prosarc.com.co';
        $user->FK_UserPers = 9;
        $user->UsRol2 = 'IngenieroHSEQ';
        $user->UsRolDesc2 = 'Ingeniero de HSEQ';
        $user->DeleteUser = 0;
        $user->save();
    }
}
